<?php

use Illuminate\Database\Seeder;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
          ['name'=> 'system/permission', 'display_name'=> '权限管理', 'description'=> '权限管理', 'ismenu'=> 1],
          ['name'=> 'system/role', 'display_name'=> '角色管理', 'description'=> '角色管理', 'ismenu'=> 1],
          ['name'=> 'system/account', 'display_name'=> '账号管理', 'description'=> '账号管理', 'ismenu'=> 1],
          ['name'=> 'data_manage', 'display_name'=> '数据维护', 'description'=> '数据维护', 'ismenu'=> 1],
          ['name'=> 'business', 'display_name'=> '业务管理', 'description'=> '业务管理', 'ismenu'=> 1],
          ['name'=> '/', 'display_name'=> '首页访问', 'description'=> '首页访问', 'ismenu'=> 0],
          ['name'=> 'report', 'display_name'=> '报表管理', 'description'=> '报表管理', 'ismenu'=> 1],
          ['name'=> 'finance/transport', 'display_name'=> '运费登记', 'description'=> '运费登记', 'ismenu'=> 1],
          ['name'=> 'finance/pay', 'display_name'=> '付款管理', 'description'=> '付款管理', 'ismenu'=> 1],
          ['name'=> 'finance/receipt', 'display_name'=> '收汇登记', 'description'=> '收汇登记', 'ismenu'=> 1],
          ['name'=> 'finance/remittee', 'display_name'=> '收款方管理', 'description'=> '收款方管理', 'ismenu'=> 1],
          ['name'=> 'rebate', 'display_name'=> '退税管理', 'description'=> '退税管理', 'ismenu'=> 1],
          ['name'=> 'filing', 'display_name'=> '申报管理', 'description'=> '申报管理', 'ismenu'=> 1],
          ['name'=> 'invoice', 'display_name'=> '发票管理', 'description'=> '发票管理', 'ismenu'=> 1],
          ['name'=> 'clearance', 'display_name'=> '报关管理', 'description'=> '报关管理', 'ismenu'=> 1],
          ['name'=> 'order', 'display_name'=> '订单管理', 'description'=> '订单管理', 'ismenu'=> 1],
          ['name'=> 'drawer', 'display_name'=> '开票人管理', 'description'=> '开票人管理', 'ismenu'=> 1],
          ['name'=> 'product', 'display_name'=> '产品管理', 'description'=> '产品管理', 'ismenu'=> 1],
          ['name'=> 'customer', 'display_name'=> '客户管理', 'description'=> '客户管理', 'ismenu'=> 1],
          ['name'=> 'system/permission/save', 'display_name'=> '权限管理-新增权限', 'description'=> '权限管理-新增权限', 'ismenu'=> 0],
          ['name'=> 'system/permission/update', 'display_name'=> '权限管理-修改权限', 'description'=> '权限管理-修改权限', 'ismenu'=> 0],
          ['name'=> 'system/permission/delete', 'display_name'=> '权限管理-删除权限', 'description'=> '权限管理-删除权限', 'ismenu'=> 0],
          ['name'=> 'system/role/save', 'display_name'=> '角色管理-新增角色', 'description'=> '角色管理-新增角色', 'ismenu'=> 0],
          ['name'=> 'system/role/update', 'display_name'=> '角色管理-修改角色', 'description'=> '角色管理-修改角色', 'ismenu'=> 0],
          ['name'=> 'system/role/delete', 'display_name'=> '角色管理-删除角色', 'description'=> '角色管理-删除角色', 'ismenu'=> 0],
          ['name'=> 'system/account/save', 'display_name'=> '账号管理-新增账号', 'description'=> '账号管理-新增账号', 'ismenu'=> 0],
          ['name'=> 'system/account/update', 'display_name'=> '账号管理-修改账号', 'description'=> '账号管理-修改账号', 'ismenu'=> 0],
          ['name'=> 'system/account/delete', 'display_name'=> '账号管理-删除账号', 'description'=> '账号管理-删除账号', 'ismenu'=> 0],
          ['name'=> 'data', 'display_name'=> '数据维护-添加、修改、删除', 'description'=> '数据维护-添加、修改、删除', 'ismenu'=> 0],
          ['name'=> 'business/save', 'display_name'=> '业务管理-新增项目', 'description'=> '业务管理-新增项目', 'ismenu'=> 0],
          ['name'=> 'business/update', 'display_name'=> '业务管理-修改项目', 'description'=> '业务管理-修改项目', 'ismenu'=> 0],
          ['name'=> 'business/delete', 'display_name'=> '业务管理-删除项目', 'description'=> '业务管理-删除项目', 'ismenu'=> 0],
          ['name'=> 'finance/transport/save', 'display_name'=> '财务管理-运费登记-新增', 'description'=> '财务管理-运费登记-新增', 'ismenu'=> 0],
          ['name'=> 'finance/transport/read', 'display_name'=> '财务管理-运费登记-查看', 'description'=> '财务管理-运费登记-查看', 'ismenu'=> 0],
          ['name'=> 'finance/transport/approve', 'display_name'=> '财务管理-运费登记-审核', 'description'=> '财务管理-运费登记-审核', 'ismenu'=> 0],
          ['name'=> 'finance/transport/update', 'display_name'=> '财务管理-运费登记-修改', 'description'=> '财务管理-运费登记-修改', 'ismenu'=> 0],
          ['name'=> 'finance/pay/save', 'display_name'=> '财务管理-付款管理-新增', 'description'=> '财务管理-付款管理-新增', 'ismenu'=> 0],
          ['name'=> 'finance/pay/read', 'display_name'=> '财务管理-付款管理-查看', 'description'=> '财务管理-付款管理-查看', 'ismenu'=> 0],
          ['name'=> 'finance/pay/approve', 'display_name'=> '财务管理-付款管理-审核', 'description'=> '财务管理-付款管理-审核', 'ismenu'=> 0],
          ['name'=> 'finance/pay/update', 'display_name'=> '财务管理-付款管理-修改', 'description'=> '财务管理-付款管理-修改', 'ismenu'=> 0],
          ['name'=> 'finance/receipt/save', 'display_name'=> '财务管理-收汇登记-新增', 'description'=> '财务管理-收汇登记-新增', 'ismenu'=> 0],
          ['name'=> 'finance/receipt/read', 'display_name'=> '财务管理-收汇登记-查看', 'description'=> '财务管理-收汇登记-查看', 'ismenu'=> 0],
          ['name'=> 'finance/receipt/update', 'display_name'=> '财务管理-收汇登记-修改', 'description'=> '财务管理-收汇登记-修改', 'ismenu'=> 0],
          ['name'=> 'finance/receipt/delete', 'display_name'=> '财务管理-收汇登记-删除', 'description'=> '财务管理-收汇登记-删除', 'ismenu'=> 0],
          ['name'=> 'finance/receipt/number', 'display_name'=> '财务管理-收汇登记-关联订单详情', 'description'=> '财务管理-收汇登记-关联订单详情', 'ismenu'=> 0],
          ['name'=> 'finance/receipt/binding', 'display_name'=> '财务管理-收汇登记-绑定订单', 'description'=> '财务管理-收汇登记-绑定订单', 'ismenu'=> 0],
          ['name'=> 'finance/receipt/unbinding', 'display_name'=> '财务管理-收汇登记-解绑订单', 'description'=> '财务管理-收汇登记-解绑订单', 'ismenu'=> 0],
          ['name'=> 'finance/remittee/save', 'display_name'=> '财务管理-收款方管理-新增', 'description'=> '财务管理-收款方管理-新增', 'ismenu'=> 0],
          ['name'=> 'finance/remittee/update', 'display_name'=> '财务管理-收款方管理-修改', 'description'=> '财务管理-收款方管理-修改', 'ismenu'=> 0],
          ['name'=> 'finance/remittee/delete', 'display_name'=> '财务管理-收款方管理-删除', 'description'=> '财务管理-收款方管理-删除', 'ismenu'=> 0],
          ['name'=> 'rebate/update', 'display_name'=> '退税管理-退税登记', 'description'=> '退税管理-退税登记', 'ismenu'=> 0],
          ['name'=> 'rebate/refund', 'display_name'=> '退税管理-退税报表下载', 'description'=> '退税管理-退税报表下载', 'ismenu'=> 0],
          ['name'=> 'filing/save', 'display_name'=> '申报管理-申报登记', 'description'=> '申报管理-申报登记', 'ismenu'=> 0],
          ['name'=> 'invoice/choose', 'display_name'=> '发票管理-选择发票', 'description'=> '发票管理-选择发票', 'ismenu'=> 0],
          ['name'=> 'filing/read', 'display_name'=> '申报管理-查看', 'description'=> '申报管理-查看', 'ismenu'=> 0],
          ['name'=> 'filing/update', 'display_name'=> '申报管理-退税', 'description'=> '申报管理-退税', 'ismenu'=> 0],
          ['name'=> 'filing/select', 'display_name'=> '申报管理-选择', 'description'=> '申报管理-选择', 'ismenu'=> 0],
          ['name'=> 'filing/delete', 'display_name'=> '申报管理-删除', 'description'=> '申报管理-删除', 'ismenu'=> 0],
          ['name'=> 'filing/number', 'display_name'=> '申报管理-number', 'description'=> '申报管理-number', 'ismenu'=> 0],
          ['name'=> 'invoice/save', 'display_name'=> '发票管理-登记发票', 'description'=> '发票管理-登记发票', 'ismenu'=> 0],
          ['name'=> 'company/choose', 'display_name'=> '发票管理-开票工厂选择', 'description'=> '发票管理-开票工厂选择', 'ismenu'=> 0],
          ['name'=> 'drawer_order/choose', 'display_name'=> '发票管理-订单号选择', 'description'=> '发票管理-订单号选择', 'ismenu'=> 0],
          ['name'=> 'data/father', 'display_name'=> '数据维护-父节点数据', 'description'=> '数据维护-父节点数据', 'ismenu'=> 0],
          ['name'=> 'invoice/read', 'display_name'=> '发票管理-查看', 'description'=> '发票管理-查看', 'ismenu'=> 0],
          ['name'=> 'invoice/approve', 'display_name'=> '发票管理-审核', 'description'=> '发票管理-审核', 'ismenu'=> 0],
          ['name'=> 'invoice/delete', 'display_name'=> '发票管理-删除', 'description'=> '发票管理-删除', 'ismenu'=> 0],
          ['name'=> 'invoice/update', 'display_name'=> '发票管理-修改', 'description'=> '发票管理-修改', 'ismenu'=> 0],
          ['name'=> 'invoice_clearances', 'display_name'=> '发票管理-报关', 'description'=> '发票管理-报关', 'ismenu'=> 0],
          ['name'=> 'clearance/read', 'display_name'=> '报关管理-查看', 'description'=> '报关管理-查看', 'ismenu'=> 0],
          ['name'=> 'clearance/file', 'display_name'=> '报关管理-备案资料', 'description'=> '报关管理-备案资料', 'ismenu'=> 0],
          ['name'=> 'clearance/dwxlsx', 'display_name'=> '报关管理-下载报关资料', 'description'=> '报关管理-下载报关资料', 'ismenu'=> 0],
          ['name'=> 'clearance/update', 'display_name'=> '报关管理-修改', 'description'=> '报关管理-修改', 'ismenu'=> 0],
          ['name'=> 'order/save', 'display_name'=> '订单管理-添加', 'description'=> '订单管理-添加', 'ismenu'=> 0],
          ['name'=> 'order/read', 'display_name'=> '订单管理-查看', 'description'=> '订单管理-查看', 'ismenu'=> 0],
          ['name'=> 'drawer/choose', 'display_name'=> '订单管理-选择需出货的产品', 'description'=> '订单管理-选择需出货的产品', 'ismenu'=> 0],
          ['name'=> 'customer/choose', 'display_name'=> '客户列表选择', 'description'=> '客户列表选择', 'ismenu'=> 0],
          ['name'=> 'order/update', 'display_name'=> '订单管理-修改、结案', 'description'=> '订单管理-修改、结案', 'ismenu'=> 0],
          ['name'=> 'order/delete', 'display_name'=> '订单管理-删除', 'description'=> '订单管理-删除', 'ismenu'=> 0],
          ['name'=> 'order/approve', 'display_name'=> '订单管理-审核', 'description'=> '订单管理-审核', 'ismenu'=> 0],
          ['name'=> 'drawer/save', 'display_name'=> '开票人管理-添加开票人', 'description'=> '开票人管理-添加开票人', 'ismenu'=> 0],
          ['name'=> 'product/choose', 'display_name'=> '产品列表选择', 'description'=> '产品列表选择', 'ismenu'=> 0],
          ['name'=> 'drawer/read', 'display_name'=> '开票人管理-查看', 'description'=> '开票人管理-查看', 'ismenu'=> 0],
          ['name'=> 'drawer/approve', 'display_name'=> '开票人管理-审核', 'description'=> '开票人管理-审核', 'ismenu'=> 0],
          ['name'=> 'drawer/update', 'display_name'=> '开票人管理-修改', 'description'=> '开票人管理-修改', 'ismenu'=> 0],
          ['name'=> 'drawer_products', 'display_name'=> '开票的所有产品', 'description'=> '开票的所有产品', 'ismenu'=> 0],
          ['name'=> 'product/save', 'display_name'=> '产品管理-添加产品', 'description'=> '产品管理-添加产品', 'ismenu'=> 0],
          ['name'=> 'product/read', 'display_name'=> '产品管理-查看', 'description'=> '产品管理-查看', 'ismenu'=> 0],
          ['name'=> 'product/approve', 'display_name'=> '产品管理-审核', 'description'=> '产品管理-审核', 'ismenu'=> 0],
          ['name'=> 'product/update', 'display_name'=> '产品管理-修改', 'description'=> '产品管理-修改', 'ismenu'=> 0],
          ['name'=> 'product/delete', 'display_name'=> '产品管理-删除', 'description'=> '产品管理-删除', 'ismenu'=> 0],
          ['name'=> 'customer/save', 'display_name'=> '客户管理-新增客户', 'description'=> '客户管理-新增客户', 'ismenu'=> 0],
          ['name'=> 'chosalesman', 'display_name'=> '客户管理-批量分配客户', 'description'=> '客户管理-批量分配客户', 'ismenu'=> 0],
          ['name'=> 'customer/read', 'display_name'=> '客户管理-查看', 'description'=> '客户管理-查看', 'ismenu'=> 0],
          ['name'=> 'customer/update', 'display_name'=> '客户管理-修改', 'description'=> '客户管理-修改', 'ismenu'=> 0],
          ['name'=> 'customer/approve', 'display_name'=> '客户管理-审核', 'description'=> '客户管理-审核', 'ismenu'=> 0],
          ['name'=> 'customer/number', 'display_name'=> '客户管理-number', 'description'=> '客户管理-number', 'ismenu'=> 0],
          ['name'=> 'finance/receipt/order', 'display_name'=> '财务管理-收汇登记-关联订单操作', 'description'=> '财务管理-收汇登记-关联订单操作', 'ismenu'=> 0],
          ['name'=> 'clearance/xjentering', 'display_name'=> '报关管理-新建报关录入', 'description'=> '报关管理-新建报关录入', 'ismenu'=> 0],
          ['name'=> 'business/contract', 'display_name'=> '业务管理-合同号', 'description'=> '业务管理-合同号', 'ismenu'=> 0],
          ['name'=> 'order/choose', 'display_name'=> '订单选择', 'description'=> '订单选择', 'ismenu'=> 0],
          ['name'=> 'rebate/read', 'display_name'=> '退税管理 查看', 'description'=> '退税管理 查看', 'ismenu'=> 0],
          ['name'=> 'rebate/save', 'display_name'=> '退税管理 - 新增退税登记', 'description'=> '退税管理 - 新增退税登记', 'ismenu'=> 0],
          ['name'=> 'trader', 'display_name'=> '贸易商管理', 'description'=> '贸易商管理', 'ismenu'=> 1],
          ['name'=> 'trader/save', 'display_name'=> '贸易商管理-添加贸易商', 'description'=> '贸易商管理-添加贸易商', 'ismenu'=> 0],
          ['name'=> 'trader/update', 'display_name'=> '贸易商管理-修改贸易商', 'description'=> '贸易商管理-修改贸易商', 'ismenu'=> 0],
          ['name'=> 'billing', 'display_name'=> '开票资料管理', 'description'=> '开票资料管理', 'ismenu'=> 1],
          ['name'=> 'billing/save', 'display_name'=> '开票资料管理-新增', 'description'=> '开票资料管理-新增', 'ismenu'=> 0],
          ['name'=> 'billing/update', 'display_name'=> '开票资料管理-修改', 'description'=> '开票资料管理-修改', 'ismenu'=> 0],
          ['name'=> 'order/harbor', 'display_name'=> '订单管理-港口信息', 'description'=> '订单管理-港口信息', 'ismenu'=> 0],
          ['name'=> 'notification', 'display_name'=> '消息通知', 'description'=> '消息通知', 'ismenu'=> 0],
          ['name'=> 'finance/settlement', 'display_name'=> '财务管理-退税结算', 'description'=> '财务管理-退税结算', 'ismenu'=> 1],
        ]);
    }
}
